name: discord test

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Bot
        uses: tsickert/discord-webhook@4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_REPORTSERVER }}
