name: discord report

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    branches: main
    types:
      - completed

jobs:
  success:
    f: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_REPORTSERVER }}
          content: "Test"
