name: Test site(s) for errors

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    branches: main
    types:
      - completed

jobs:
  test-site:
    # if ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: test if build was good
      run: echo "hello"
    
